name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Configurar Docker
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Construir y Publicar Backend
        run: |
          docker build -t ${{ secrets.REGISTRY_USERNAME }}/backend -f Dockerfile-backend .
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker push ${{ secrets.REGISTRY_USERNAME }}/backend

      - name: Construir y Publicar Frontend
        run: |
          docker build -t ${{ secrets.REGISTRY_USERNAME }}/frontend -f Dockerfile-frontend .
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker push ${{ secrets.REGISTRY_USERNAME }}/frontend

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Configurar Docker
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Iniciar Contenedores
        run: |
          docker run -d --name backend ${{ secrets.REGISTRY_USERNAME }}/backend
          docker run -d --name frontend -p 80:80 ${{ secrets.REGISTRY_USERNAME }}/frontend
